/**
 * Cross-implementation conformance: the JS verifier must agree with the Python
 * one on every bundle, verdict for verdict.
 *
 * Fixtures are generated by the Python reference builder (see gen_fixtures.py),
 * so this is a genuine two-implementation comparison, not a self-check.
 */
import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { verifyBundle, rederiveGateVerdict, erfc, checkKappaK, canon, pyFloatRepr,
         verifyIntervalBoundCert } from "../src/lcert.js";

const here = dirname(fileURLToPath(import.meta.url));
const FIX = join(here, "fixtures");

let pass = 0, fail = 0;
const fails = [];

function check(name, cond, detail = "") {
  if (cond) { pass++; }
  else { fail++; fails.push(`${name}${detail ? " — " + detail : ""}`); }
}

/* ---- 1. erfc agreement with Python's math.erfc ---- */
const erfcRef = JSON.parse(readFileSync(join(FIX, "erfc_reference.json"), "utf8"));
let worstErfc = 0;
for (const [xs, want] of erfcRef) {
  const got = erfc(Number(xs));
  const absErr = Math.abs(got - want);
  worstErfc = Math.max(worstErfc, absErr);
  check(`erfc(${xs})`, absErr < 1e-12, `abs err ${absErr.toExponential(3)}`);
}

/* ---- 2. verdict agreement on every generated bundle ---- */
const cases = JSON.parse(readFileSync(join(FIX, "cases.json"), "utf8"));
for (const c of cases) {
  const bundleText = readFileSync(join(FIX, c.dir, "bundle.json"), "utf8");
  const files = {};
  for (const rel of Object.keys(JSON.parse(bundleText).manifest || {}))
    files[rel] = new Uint8Array(readFileSync(join(FIX, c.dir, rel)));

  const res = await verifyBundle(bundleText, files);
  check(`bundle ${c.dir} ok`, res.ok === c.python_ok,
        `js ok=${res.ok} python ok=${c.python_ok} errs=${JSON.stringify(res.errors)}`);

  for (const cert of JSON.parse(bundleText).gate_certs || []) {
    const red = rederiveGateVerdict(cert);
    const want = c.python_verdicts[cert.name];
    for (const k of Object.keys(want))
      check(`${c.dir}/${cert.name}.${k}`, red[k] === want[k],
            `js=${red[k]} python=${want[k]}`);
  }
}

/* ---- 3. canonical JSON must match Python's separators=(',',':') ---- */
// ---- LCERT-BOUND-1: the domain-agnostic certificate kind --------------------
// The Python and JS re-derivations must agree exactly, including on the margin
// that decides admission. These cases include a locus exactly ON the threshold
// and one a single ULP inside it.
const boundCases = JSON.parse(readFileSync(join(FIX, "bound_cases.json"), "utf8"));
for (const c of boundCases) {
  const errs = verifyIntervalBoundCert(c.cert);
  check(`bound ${c.dir} agrees`, errs.length === 0,
        `JS found ${errs.length} error(s) where Python found none: ${errs[0] ?? ""}`);

  // and the re-derivation must reject the same tampering Python rejects
  const overstated = JSON.parse(JSON.stringify(c.cert));
  overstated.recorded.worst_margin = 1e9;
  check(`bound ${c.dir} rejects an overstated margin`,
        verifyIntervalBoundCert(overstated).some(e => e.includes("E_MARGIN_OVERSTATED")));

  const flipped = JSON.parse(JSON.stringify(c.cert));
  flipped.recorded.admit = !flipped.recorded.admit;
  check(`bound ${c.dir} rejects a flipped admit`,
        verifyIntervalBoundCert(flipped).some(e => e.includes("recorded admit")));
}

const canonRef = JSON.parse(readFileSync(join(FIX, "canon_reference.json"), "utf8"));
for (const [objText, want] of canonRef)
  check(`canon ${want.slice(0, 40)}`, canon(JSON.parse(objText)) === want,
        `got ${canon(JSON.parse(objText))}`);

/* ---- 2b. vacuity guard: a bundle with no certificates must be refused ---- */
{
  const dir = JSON.parse(readFileSync(join(FIX, "cases.json"), "utf8"))[0].dir;
  const b = JSON.parse(readFileSync(join(FIX, dir, "bundle.json"), "utf8"));
  b.gate_certs = [];
  const files = { "preregistration.json":
    new Uint8Array(readFileSync(join(FIX, dir, "preregistration.json"))) };
  const strict = await verifyBundle(JSON.stringify(b), files);
  check("vacuous bundle refused by default", strict.ok === false,
        `ok=${strict.ok}`);
  check("vacuous bundle reports zero certificates", strict.nCertificates === 0);
  const lax = await verifyBundle(JSON.stringify(b), files, "", { requireCerts: false });
  check("vacuous bundle allowed when requested", lax.errors.every(e => !e.includes("vacuous")));
}

/* ---- 2c. verdict taxonomy: abstain without an anchor, assert only with one ---- */
{
  const dir = JSON.parse(readFileSync(join(FIX, "cases.json"), "utf8"))[0].dir;
  const txt = readFileSync(join(FIX, dir, "bundle.json"), "utf8");
  const files = { "preregistration.json":
    new Uint8Array(readFileSync(join(FIX, dir, "preregistration.json"))) };
  const { createHash } = await import("node:crypto");
  const fp = createHash("sha256").update(readFileSync(join(FIX, dir, "bundle.json"))).digest("hex");

  const un = await verifyBundle(txt, files);
  check("unanchored abstains", un.verdict === "UNVERIFIED", `got ${un.verdict}`);
  check("unanchored is not ok", un.ok === false);
  check("unanchored still reports internal consistency", un.internallyConsistent === true);
  check("unanchored names the missing anchor", un.trustAnchor === "NONE");

  const an = await verifyBundle(txt, files, fp);
  check("anchored verifies", an.verdict === "VERIFIED", `got ${an.verdict}`);
  check("anchored reports the anchor", an.trustAnchor === "fingerprint");

  // the self-consistent forgery: internally perfect, refuted only by the anchor
  const b = JSON.parse(txt);
  b.gate_certs[0].loci.I_lo = [0.29]; b.gate_certs[0].loci.I_hi = [0.31];
  const red = rederiveGateVerdict(b.gate_certs[0]);
  b.gate_certs[0].recorded = Object.assign({}, red,
    { float_admit: red.interval_admit, match: true });
  const forged = JSON.stringify(b);
  const fu = await verifyBundle(forged, files);
  check("forgery unanchored abstains", fu.verdict === "UNVERIFIED", `got ${fu.verdict}`);
  check("forgery unanchored is never VERIFIED", fu.verdict !== "VERIFIED");
  const fa = await verifyBundle(forged, files, fp);
  check("forgery anchored is refuted", fa.verdict === "REFUTED", `got ${fa.verdict}`);
}

/* ---- 3b. Python-compatible float rendering ---- */
const floatRef = JSON.parse(readFileSync(join(FIX, "float_repr_reference.json"), "utf8"));
for (const [lit, want] of floatRef) {
  const got = pyFloatRepr(Number(lit));
  check(`pyFloatRepr(${lit})`, got === want, `got ${got} want ${want}`);
}

/* ---- 4. kappa/K checks reject tampering ---- */
const kk = JSON.parse(readFileSync(join(FIX, "kappa_cases.json"), "utf8"));
for (const t of kk) {
  const errs = checkKappaK(t.budget, t.safety, t.n_photons, t.kappa, t.K);
  check(`kappaK ${t.label}`, (errs.length === 0) === t.python_clean,
        `js errs=${errs.length} python_clean=${t.python_clean}`);
}

console.log(`worst erfc abs error vs Python: ${worstErfc.toExponential(3)}`);
console.log(`${pass} passed, ${fail} failed`);
if (fail) { for (const f of fails.slice(0, 20)) console.error("  FAIL " + f); process.exit(1); }
